version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-web
    working_dir: /app/webserver
    command: flask run --host 0.0.0.0
    # ports:
    #   - "5000:5000"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-dashboard
    working_dir: /app/dashboard
    command: python app.py --host=0.0.0.0
    # ports:
    #   - "8050:8050"

  nginx:
    image: nginx:latest
    container_name: dash-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/static:/app/static
